### ISSUE TITLE
Code 127 bun command not found

### ISSUE THREAD

**Issue by sam1am** [dcrebbin/meta-vision-api#2]
sam@smol:/mnt/c/Users/gthin/Documents/Github/meta-vision-api$ bun run dev
$ bun run ./src/index.ts
/usr/bin/bash: line 1: bun: command not found
error: script "dev" exited with code 127

bun is installed and appears to be working. Bun install worked, but on run i see this error.

**Comment by sam1am** [comment]
I believe the error is from the line:
`import { readFile, writeFile } from "fs/promises";`

What is this dependency? Thats what im missing.

**Comment by Jarred-Sumner** [comment]
ARe you sure that `bun` is in `$PATH`?

**Comment by dcrebbin** [comment]
Appears to be an install with your bun install like Jarred said

@sam1am any progress on this?
