### ISSUE TITLE
send a photo ?

### ISSUE THREAD

**Issue by ilker-aktuna** [dcrebbin/meta-vision-api#4]
On my Rayban stories , "send a photo" command sends a message. It does not send a photo.
How do you do that ?

**Comment by dcrebbin** [comment]
Are these an older version of: https://www.meta.com/au/smart-glasses/ when they were called Stories?

I only made the API for these versions so I'm not aware if there's any compatibility with older models.

**Comment by ilker-aktuna** [comment]
Well, how do you call the assistant on the glasses ?
is it "hey facebook" or is it "hey meta" ?

**Comment by dcrebbin** [comment]
This hack requires the latest Meta Raybans with the ability to send photos on messenger via a voice command.

Older models are not compatible to my knowledge.

**Comment by ilker-aktuna** [comment]
thanks. I hope they upgrade it sometime..
